-- MySQL INSERT & UPDATE TABLE
-- TAFF_DATA DATABASE FOR ACCESSCONTROL (Update 02/06/2025)
USE taff_data;

-- 1 INSERT DATA INTO TABLE (Update 21/02/2018)
INSERT INTO taff_data.dbusers (user_name,pass_word,user_right,st_date,ex_date,user_status,user_admin,dep_code,sec_code,monitor_location,monitor_data,control_reader)  
VALUES ('admin',CONCAT('*',UPPER(SHA1(UNHEX(SHA1('admin')),'0',CURRENT_DATE(),CURRENT_DATE()+INTERVAL 1 YEAR,'0','1','','','','1','');
INSERT INTO taff_data.dbcompany (com_code) VALUES('0');
INSERT INTO taff_data.dbconfigcorp (config_code) VALUES('0');
INSERT INTO taff_data.dbdepart (dep_code, th_desc, en_desc) VALUES('000001', 'ค่าเริ่มต้น', 'Default');
INSERT INTO taff_data.dbsection (sec_code, th_desc, en_desc, dep_code) VALUES('000001', 'ค่าเริ่มต้น', 'Default', '000001');
INSERT INTO taff_data.dbposition (pos_code, th_desc, en_desc) VALUES('000001', 'พนักงาน', 'Employee');
INSERT INTO taff_data.dbtype (type_code, th_desc, en_desc) VALUES('000001', 'พนักงานประจำ', 'Full Time');
INSERT INTO taff_data.dbgroup (group_code, th_desc, en_desc) VALUES('000000', 'ไม่มีสิทธิ์เข้า', 'No Access');
INSERT INTO taff_data.dbgroup (group_code, th_desc, en_desc) VALUES('000001', 'มีสิทธิ์เข้าได้ทุกประตู ตลอด 24 ชั่วโมง', '24 Hours All Access');
INSERT INTO taff_data.dbgroup (group_code, th_desc, en_desc) VALUES('groupblacklist', 'พนักงานติดบัญชีดำ', 'Employee Blacklisted');
INSERT INTO taff_data.dbtimedesc (time_id, th_desc, en_desc, time1, pin_flag1, fp_flag1) VALUES('01', '24 ชั่วโมง', '24 Hours', '00002359', '1', '1');
INSERT INTO taff_data.dbtimezonedesc (time_code, th_desc, en_desc) VALUES('01', 'มีสิทธิ์เข้าได้ทุกประตู ตลอด 24 ชั่วโมง', '24 Hours All Access');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '1', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '2', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '3', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '4', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '5', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '6', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '7', '01');
INSERT INTO taff_data.dbtimezone (time_code, day_type, time_id) VALUES('01', '8', '01');
INSERT INTO taff_data.dblock (day_type) VALUES('1');
INSERT INTO taff_data.dblock (day_type) VALUES('2');
INSERT INTO taff_data.dblock (day_type) VALUES('3');
INSERT INTO taff_data.dblock (day_type) VALUES('4');
INSERT INTO taff_data.dblock (day_type) VALUES('5');
INSERT INTO taff_data.dblock (day_type) VALUES('6');
INSERT INTO taff_data.dblock (day_type) VALUES('7');
INSERT INTO taff_data.dblock (day_type) VALUES('8');
INSERT INTO taff_data.dbunlock (day_type) VALUES('1');
INSERT INTO taff_data.dbunlock (day_type) VALUES('2');
INSERT INTO taff_data.dbunlock (day_type) VALUES('3');
INSERT INTO taff_data.dbunlock (day_type) VALUES('4');
INSERT INTO taff_data.dbunlock (day_type) VALUES('5');
INSERT INTO taff_data.dbunlock (day_type) VALUES('6');
INSERT INTO taff_data.dbunlock (day_type) VALUES('7');
INSERT INTO taff_data.dbunlock (day_type) VALUES('8');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('1');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('2');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('3');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('4');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('5');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('6');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('7');
INSERT INTO taff_data.dbtimeon_out4 (day_type) VALUES('8');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('01', 'ผ่านโดยการวางบัตร', 'Success by card', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('02', 'ผ่านโดยการวางนิ้ว', 'Success by finger', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('03', 'ผ่านโดยการกดรหัส', 'Success by keyboard', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('04', 'ผ่านโดยการวางบัตร + นิ้วมือ', 'Success by card + finger', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('05', 'ผ่านโดยการกดรหัส + นิ้วมือ', 'Success by keyboard + finger', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('06', 'ติดบัญชีดำ', 'Error blacklist', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('07', 'ผ่านโดยบาร์โค้ด', 'Success by barcode', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('08', '', '', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('09', 'ใช้บัตร Master Card', 'Master Card', '1000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('10', 'ตรวจพบรหัส', 'Detect ID', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('11', 'รูปแบบของรหัสบัตร ไม่ตรงกับที่กำหนดในระบบ', 'Card pattern mismatch', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('12', 'บัตรหมดอายุ ไม่สามารถใช้งานได้', 'Card expire DATE', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('13', 'บัตรยังไม่ถึงวันเริ่มใช้งาน', 'Card start DATE', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('14', 'ลำดับการออกบัตร ไม่ตรงกับที่กำหนดในระบบ', 'Card issue error', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('15', 'ระบบงานที่กำหนดไว้ในบัตร ไม่ตรงกับใน Reader', 'Card application mismatch', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('16', 'รหัสบริษัทที่กำหนดในบัตร ไม่ตรงกับใน Reader', 'Card customer mismatch', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('17', 'ระบบอ่านข้อมูลบัตรยังไม่สมบูรณ์', 'Card remove before end process', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('18', 'วางบัตร แต่ไม่ได้วางนิ้ว', 'Pass card not press finger', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('19', 'วางบัตร แต่ไม่ได้กดรหัสผ่าน', 'Pass card not press pincode', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('20', 'กดรหัสผ่านไม่ถูกต้อง', 'Pincode error', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('21', 'ไม่ได้กำหนดรหัสนี้ไว้ในตารางข้อมูล', 'ID. table mismatch', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('22', 'ช่วงเวลาที่กำหนดไม่อนุญาติให้ผ่าน', 'Timezone mismatch', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('23', 'ลายนิ้วมือไม่ถูกต้อง', 'Finger-print mismatch', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('24', 'ระบบ Anti-Passback ไม่ถูกต้อง ไม่สามารถผ่านได้', 'Anti-passback error', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('25', 'MU ติดต่อกับ CRU1 ไม่ได้', 'CRU1 disconnect', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('26', 'MU ติดต่อกับ CRU1 ได้ตามปกติ', 'CRU1 connect', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('27', 'MU ติดต่อกับ CRU2 ไม่ได้', 'CRU2 disconnect', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('28', 'MU ติดต่อกับ CRU2 ได้ตามปกติ', 'CRU2 connect', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('29', 'ปุ่มเปิดประตูถูกกด', 'Switch press (Input#1)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('30', 'ปุ่มเปิดประตูถูกปล่อย', 'Switch release (Input#1)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('31', 'ประตูเปิด', 'Door open (Input#2)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('32', 'ประตูปิด', 'Door close (Input#2)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('33', 'ชุดล็อคประตูไฟฟ้าทำงาน', 'Bolt lock (Output#1)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('34', 'ชุดล็อคประตูไฟฟ้าถูกปลด', 'Bolt unlock (Output#1)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('35', 'สัญญาณเตือนที่ประตูดัง', 'Alarm buzzer on (Output#2)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('36', 'สัญญาณเตือนที่ประตูเงียบ', 'Alarm buzzer off (Output#2)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('37', 'ระบบ Fire alarm ตึก ส่งสัญญาณเข้า', 'Fire alarm on (Input#3)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('38', 'ระบบ Fire alarm ตึก หยุดส่งสัญญาณเข้า', 'Fire alarm off (Input#3)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('39', 'On (Input#4)', 'On (Input#4)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('40', 'Off (Input#4)', 'Off (Input#4)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('41', 'ระบบไฟฟ้าทำงานตามปกติ', 'Power on', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('42', 'ระบบไฟฟ้าหยุดทำงาน', 'Power off', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('43', 'ระบบสั่งกระดิ่งดัง', 'Bell on (Output#3)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('44', 'ระบบสั่งกระดิ่งหยุดดัง', 'Bell off (Output#3)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('45', 'On (Output#4)', 'On (Output#4)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('46', 'Off (Output#4)', 'Off (Output#4)', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('47', 'เพิ่มรหัสพนักงานที่หัวอ่าน', 'Upload ID Table', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('48', 'ปุ่ม Door Bell บน Reader ถูกกด', 'Door bell button press', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('49', 'ปุ่มฉุกเฉิน บน Reader ถูกกด', 'Emergency button press', '0000100000');
INSERT INTO taff_data.dbevent (event_code, th_desc, en_desc, event_act) VALUES ('50', 'เครื่องถูกถอดออกจากที่ติดตั้ง', 'Tamper switch on', '0000100000');

-- 2 UPDATE DATA INTO TABLE (Update 21/02/2018)
UPDATE taff_data.dbevent SET software_act = '0000011000' WHERE (event_code <= '08') AND (software_act = '0000000000');
UPDATE taff_data.dbevent SET software_act = '0000001000' WHERE (event_code = '06' OR event_code > '08') AND (software_act = '0000000000');
UPDATE taff_data.dbevent SET th_desc = 'ติดบัญชีดำ', en_desc = 'Error blacklist', event_act = '0000100000' WHERE (event_code = '06');
UPDATE taff_data.dbevent SET th_desc = 'ผ่านโดยบาร์โค้ด', en_desc = 'Success by barcode', event_act = '1000100000' WHERE (event_code = '07');
UPDATE taff_data.dbevent SET th_desc = '', en_desc = '', event_act = '0000100000' WHERE (event_code = '08');
UPDATE taff_data.dbevent SET group_img = '0' WHERE (event_code <= '05' OR event_code = '07' OR event_code = '26' OR event_code = '28' OR event_code = '30' OR event_code = '32' 
    OR event_code = '33' OR event_code = '36' OR event_code = '38' OR event_code = '40' OR event_code = '41' OR event_code = '44' OR event_code = '46' OR event_code = '47');
UPDATE taff_data.dbevent SET group_img = '1' WHERE (event_code = '31' OR event_code = '34');	
UPDATE taff_data.dbevent SET group_img = '2' WHERE (event_code = '35' OR event_code = '37' OR event_code = '39' OR event_code = '43' OR event_code = '45');	
UPDATE taff_data.dbevent SET group_img = '3' WHERE (event_code = '06' OR (event_code >= '08' AND event_code <= '24'));
UPDATE taff_data.dbevent SET group_img = '4' WHERE (event_code = '25' OR event_code = '27');
UPDATE taff_data.dbevent SET group_img = '5' WHERE (event_code = '29' OR event_code = '48' OR event_code = '49');
UPDATE taff_data.dbevent SET group_img = '6' WHERE (event_code = '42');
UPDATE taff_data.dbevent SET group_img = '7' WHERE (event_code = '50');

-- 3 UPDATE DATA INTO TABLE (Update 10/06/2019)
UPDATE taff_data.dbusers SET monitor_data = '1' WHERE user_name = 'admin';